# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from market import market_pb2 as market_dot_market__pb2


class MarketModuleStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunShortTermMarket = channel.unary_unary(
                '/market.MarketModule/RunShortTermMarket',
                request_serializer=market_dot_market__pb2.MarketInput.SerializeToString,
                response_deserializer=market_dot_market__pb2.MarketOutput.FromString,
                )
        self.RunLongTermMarket = channel.unary_unary(
                '/market.MarketModule/RunLongTermMarket',
                request_serializer=market_dot_market__pb2.MarketInput.SerializeToString,
                response_deserializer=market_dot_market__pb2.MarketOutput.FromString,
                )


class MarketModuleServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunShortTermMarket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunLongTermMarket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketModuleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunShortTermMarket': grpc.unary_unary_rpc_method_handler(
                    servicer.RunShortTermMarket,
                    request_deserializer=market_dot_market__pb2.MarketInput.FromString,
                    response_serializer=market_dot_market__pb2.MarketOutput.SerializeToString,
            ),
            'RunLongTermMarket': grpc.unary_unary_rpc_method_handler(
                    servicer.RunLongTermMarket,
                    request_deserializer=market_dot_market__pb2.MarketInput.FromString,
                    response_serializer=market_dot_market__pb2.MarketOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'market.MarketModule', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MarketModule(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunShortTermMarket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/market.MarketModule/RunShortTermMarket',
            market_dot_market__pb2.MarketInput.SerializeToString,
            market_dot_market__pb2.MarketOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunLongTermMarket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/market.MarketModule/RunLongTermMarket',
            market_dot_market__pb2.MarketInput.SerializeToString,
            market_dot_market__pb2.MarketOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
