# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market/market.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13market/market.proto\x12\x06market\"O\n\x12MarketInputRequest\x12\x12\n\ngis_module\x18\x01 \x01(\t\x12\x11\n\tcf_module\x18\x02 \x01(\t\x12\x12\n\nteo_module\x18\x03 \x01(\t\"\xea\x01\n\x17ShortTermMarketResponse\x12\n\n\x02Gn\x18\x01 \x01(\t\x12\n\n\x02Ln\x18\x02 \x01(\t\x12\n\n\x02Pn\x18\x03 \x01(\t\x12\x0b\n\x03QoE\x18\x04 \x01(\t\x12\x0f\n\x07optimal\x18\x05 \x01(\t\x12\x1c\n\x14plot_market_clearing\x18\x06 \x01(\t\x12\x12\n\nsettlement\x18\x07 \x01(\t\x12\x18\n\x10social_welfare_h\x18\x08 \x01(\t\x12\x14\n\x0cshadow_price\x18\t \x01(\t\x12\x0b\n\x03Tnm\x18\n \x01(\t\x12\x1e\n\x16\x61gent_operational_cost\x18\x0b \x01(\t\"\xfd\x01\n\x16LongTermMarketResponse\x12\n\n\x02Gn\x18\x01 \x01(\t\x12\n\n\x02Ln\x18\x02 \x01(\t\x12\n\n\x02Pn\x18\x03 \x01(\t\x12\x0b\n\x03QoE\x18\x04 \x01(\t\x12\x0f\n\x07optimal\x18\x05 \x01(\t\x12\x12\n\nsettlement\x18\x06 \x01(\t\x12\x18\n\x10social_welfare_h\x18\x07 \x01(\t\x12\x0b\n\x03SPM\x18\x08 \x01(\t\x12\x0b\n\x03\x41\x44G\x18\t \x01(\t\x12\x16\n\x0e\x65xpensive_prod\x18\n \x01(\t\x12\x14\n\x0cshadow_price\x18\x0b \x01(\t\x12\x0b\n\x03Tnm\x18\x0c \x01(\t\x12\x1e\n\x16\x61gent_operational_cost\x18\r \x01(\t2\xb2\x01\n\x0cMarketModule\x12Q\n\x12RunShortTermMarket\x12\x1a.market.MarketInputRequest\x1a\x1f.market.ShortTermMarketResponse\x12O\n\x11RunLongTermMarket\x12\x1a.market.MarketInputRequest\x1a\x1e.market.LongTermMarketResponseb\x06proto3')



_MARKETINPUTREQUEST = DESCRIPTOR.message_types_by_name['MarketInputRequest']
_SHORTTERMMARKETRESPONSE = DESCRIPTOR.message_types_by_name['ShortTermMarketResponse']
_LONGTERMMARKETRESPONSE = DESCRIPTOR.message_types_by_name['LongTermMarketResponse']
MarketInputRequest = _reflection.GeneratedProtocolMessageType('MarketInputRequest', (_message.Message,), {
  'DESCRIPTOR' : _MARKETINPUTREQUEST,
  '__module__' : 'market.market_pb2'
  # @@protoc_insertion_point(class_scope:market.MarketInputRequest)
  })
_sym_db.RegisterMessage(MarketInputRequest)

ShortTermMarketResponse = _reflection.GeneratedProtocolMessageType('ShortTermMarketResponse', (_message.Message,), {
  'DESCRIPTOR' : _SHORTTERMMARKETRESPONSE,
  '__module__' : 'market.market_pb2'
  # @@protoc_insertion_point(class_scope:market.ShortTermMarketResponse)
  })
_sym_db.RegisterMessage(ShortTermMarketResponse)

LongTermMarketResponse = _reflection.GeneratedProtocolMessageType('LongTermMarketResponse', (_message.Message,), {
  'DESCRIPTOR' : _LONGTERMMARKETRESPONSE,
  '__module__' : 'market.market_pb2'
  # @@protoc_insertion_point(class_scope:market.LongTermMarketResponse)
  })
_sym_db.RegisterMessage(LongTermMarketResponse)

_MARKETMODULE = DESCRIPTOR.services_by_name['MarketModule']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MARKETINPUTREQUEST._serialized_start=31
  _MARKETINPUTREQUEST._serialized_end=110
  _SHORTTERMMARKETRESPONSE._serialized_start=113
  _SHORTTERMMARKETRESPONSE._serialized_end=347
  _LONGTERMMARKETRESPONSE._serialized_start=350
  _LONGTERMMARKETRESPONSE._serialized_end=603
  _MARKETMODULE._serialized_start=606
  _MARKETMODULE._serialized_end=784
# @@protoc_insertion_point(module_scope)
