<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cf/cf.proto

namespace Cf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cf.ConvertOrcOutput</code>
 */
class ConvertOrcOutput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string best_options = 1;</code>
     */
    private $best_options = '';
    /**
     * Generated from protobuf field <code>string report = 2;</code>
     */
    private $report = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $best_options
     *     @type string $report
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cf\Cf::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string best_options = 1;</code>
     * @return string
     */
    public function getBestOptions()
    {
        return $this->best_options;
    }

    /**
     * Generated from protobuf field <code>string best_options = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBestOptions($var)
    {
        GPBUtil::checkString($var, True);
        $this->best_options = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string report = 2;</code>
     * @return string
     */
    public function getReport()
    {
        return $this->report;
    }

    /**
     * Generated from protobuf field <code>string report = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setReport($var)
    {
        GPBUtil::checkString($var, True);
        $this->report = $var;

        return $this;
    }

}

