name: grpc-module
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - attrs=21.4.0
  - black=19.10b0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.3.29
  - certifi=2020.6.20
  - click=8.0.4
  - coverage=6.3.2
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - jsonpickle=2.0.0
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - libuuid=1.0.3
  - mypy_extensions=0.4.3
  - ncurses=6.3
  - openssl=1.1.1n
  - pathspec=0.7.0
  - pip=21.2.4
  - pydantic=1.8.2
  - python=3.10.4
  - readline=8.1.2
  - regex=2022.3.15
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.2
  - tk=8.6.11
  - toml=0.10.2
  - typed-ast=1.4.3
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - tzdata=2022a
  - wheel=0.37.1
  - xz=5.2.5
  - zipp=3.7.0
  - zlib=1.2.12
  - pip:
    - grpc-interceptor==0.14.0
    - grpcio==1.44.0
    - grpcio-tools==1.44.0
    - protobuf==3.20.1