name: grpc-module
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=
  - jsonpickle=
  - pydantic=1.10.4
  - pytest=
  - pip:
    - grpcio==1.44.0
    - grpcio-tools==1.44.0
    - grpclib==0.4.3rc2
    - protobuf==3.20.1
    - python-dateutil
