<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market/market.proto

namespace Market;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>market.MarketInputRequest</code>
 */
class MarketInputRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string gis_module = 1;</code>
     */
    protected $gis_module = '';
    /**
     * Generated from protobuf field <code>string cf_module = 2;</code>
     */
    protected $cf_module = '';
    /**
     * Generated from protobuf field <code>string teo_module = 3;</code>
     */
    protected $teo_module = '';
    /**
     * Generated from protobuf field <code>string platform = 4;</code>
     */
    protected $platform = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $gis_module
     *     @type string $cf_module
     *     @type string $teo_module
     *     @type string $platform
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Market\Market::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string gis_module = 1;</code>
     * @return string
     */
    public function getGisModule()
    {
        return $this->gis_module;
    }

    /**
     * Generated from protobuf field <code>string gis_module = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGisModule($var)
    {
        GPBUtil::checkString($var, True);
        $this->gis_module = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cf_module = 2;</code>
     * @return string
     */
    public function getCfModule()
    {
        return $this->cf_module;
    }

    /**
     * Generated from protobuf field <code>string cf_module = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCfModule($var)
    {
        GPBUtil::checkString($var, True);
        $this->cf_module = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string teo_module = 3;</code>
     * @return string
     */
    public function getTeoModule()
    {
        return $this->teo_module;
    }

    /**
     * Generated from protobuf field <code>string teo_module = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTeoModule($var)
    {
        GPBUtil::checkString($var, True);
        $this->teo_module = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string platform = 4;</code>
     * @return string
     */
    public function getPlatform()
    {
        return $this->platform;
    }

    /**
     * Generated from protobuf field <code>string platform = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPlatform($var)
    {
        GPBUtil::checkString($var, True);
        $this->platform = $var;

        return $this;
    }

}

