# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager/manager.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from manager.models import manager_responses_pb2 as manager_dot_models_dot_manager__responses__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15manager/manager.proto\x12\x07manager\x1a&manager/models/manager-responses.proto2\xd1\x01\n\rManagerModule\x12V\n\x0fStartSimulation\x12\x1f.manager.StartSimulationRequest\x1a .manager.StartSimulationResponse\"\x00\x12h\n\x15StartCharacterization\x12%.manager.StartCharacterizationRequest\x1a&.manager.StartCharacterizationResponse\"\x00\x62\x06proto3')



_MANAGERMODULE = DESCRIPTOR.services_by_name['ManagerModule']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MANAGERMODULE._serialized_start=75
  _MANAGERMODULE._serialized_end=284
# @@protoc_insertion_point(module_scope)
