<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager/manager.proto

namespace GPBMetadata\Manager;

class Manager
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ó
manager/manager.protomanager"d
StartSimulationRequest
simulation_uuid (	
simulation_metadata (	
initial_data (	")
StartSimulationResponse
status ("F
StartCharacterizationRequest
	entity_id (	
entity_data (	"B
StartCharacterizationResponse
	entity_id (	
result (	"]
UpdateSimulationRequest
simulation_uuid (	
simulation_metadata (	
data (	"*
UpdateSimulationResponse
status (2 
ManagerT
StartSimulation.manager.StartSimulationRequest .manager.StartSimulationResponsef
StartCharacterization%.manager.StartCharacterizationRequest&.manager.StartCharacterizationResponseW
UpdateSimulation .manager.UpdateSimulationRequest!.manager.UpdateSimulationResponsebproto3'
        , true);

        static::$is_initialized = true;
    }
}

