# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager/manager.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15manager/manager.proto\x12\x07manager\"d\n\x16StartSimulationRequest\x12\x17\n\x0fsimulation_uuid\x18\x01 \x01(\t\x12\x1b\n\x13simulation_metadata\x18\x02 \x01(\t\x12\x14\n\x0cinitial_data\x18\x03 \x01(\t\")\n\x17StartSimulationResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\"F\n\x1cStartCharacterizationRequest\x12\x11\n\tentity_id\x18\x01 \x01(\t\x12\x13\n\x0b\x65ntity_data\x18\x02 \x01(\t\"B\n\x1dStartCharacterizationResponse\x12\x11\n\tentity_id\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t2\xc7\x01\n\x07Manager\x12T\n\x0fStartSimulation\x12\x1f.manager.StartSimulationRequest\x1a .manager.StartSimulationResponse\x12\x66\n\x15StartCharacterization\x12%.manager.StartCharacterizationRequest\x1a&.manager.StartCharacterizationResponseb\x06proto3')



_STARTSIMULATIONREQUEST = DESCRIPTOR.message_types_by_name['StartSimulationRequest']
_STARTSIMULATIONRESPONSE = DESCRIPTOR.message_types_by_name['StartSimulationResponse']
_STARTCHARACTERIZATIONREQUEST = DESCRIPTOR.message_types_by_name['StartCharacterizationRequest']
_STARTCHARACTERIZATIONRESPONSE = DESCRIPTOR.message_types_by_name['StartCharacterizationResponse']
StartSimulationRequest = _reflection.GeneratedProtocolMessageType('StartSimulationRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTSIMULATIONREQUEST,
  '__module__' : 'manager.manager_pb2'
  # @@protoc_insertion_point(class_scope:manager.StartSimulationRequest)
  })
_sym_db.RegisterMessage(StartSimulationRequest)

StartSimulationResponse = _reflection.GeneratedProtocolMessageType('StartSimulationResponse', (_message.Message,), {
  'DESCRIPTOR' : _STARTSIMULATIONRESPONSE,
  '__module__' : 'manager.manager_pb2'
  # @@protoc_insertion_point(class_scope:manager.StartSimulationResponse)
  })
_sym_db.RegisterMessage(StartSimulationResponse)

StartCharacterizationRequest = _reflection.GeneratedProtocolMessageType('StartCharacterizationRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTCHARACTERIZATIONREQUEST,
  '__module__' : 'manager.manager_pb2'
  # @@protoc_insertion_point(class_scope:manager.StartCharacterizationRequest)
  })
_sym_db.RegisterMessage(StartCharacterizationRequest)

StartCharacterizationResponse = _reflection.GeneratedProtocolMessageType('StartCharacterizationResponse', (_message.Message,), {
  'DESCRIPTOR' : _STARTCHARACTERIZATIONRESPONSE,
  '__module__' : 'manager.manager_pb2'
  # @@protoc_insertion_point(class_scope:manager.StartCharacterizationResponse)
  })
_sym_db.RegisterMessage(StartCharacterizationResponse)

_MANAGER = DESCRIPTOR.services_by_name['Manager']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STARTSIMULATIONREQUEST._serialized_start=34
  _STARTSIMULATIONREQUEST._serialized_end=134
  _STARTSIMULATIONRESPONSE._serialized_start=136
  _STARTSIMULATIONRESPONSE._serialized_end=177
  _STARTCHARACTERIZATIONREQUEST._serialized_start=179
  _STARTCHARACTERIZATIONREQUEST._serialized_end=249
  _STARTCHARACTERIZATIONRESPONSE._serialized_start=251
  _STARTCHARACTERIZATIONRESPONSE._serialized_end=317
  _MANAGER._serialized_start=320
  _MANAGER._serialized_end=519
# @@protoc_insertion_point(module_scope)
