<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager/manager.proto

namespace Manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>manager.UpdateSimulationRequest</code>
 */
class UpdateSimulationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string simulation_uuid = 1;</code>
     */
    protected $simulation_uuid = '';
    /**
     * Generated from protobuf field <code>string simulation_metadata = 2;</code>
     */
    protected $simulation_metadata = '';
    /**
     * Generated from protobuf field <code>string data = 3;</code>
     */
    protected $data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $simulation_uuid
     *     @type string $simulation_metadata
     *     @type string $data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Manager\Manager::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string simulation_uuid = 1;</code>
     * @return string
     */
    public function getSimulationUuid()
    {
        return $this->simulation_uuid;
    }

    /**
     * Generated from protobuf field <code>string simulation_uuid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSimulationUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->simulation_uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string simulation_metadata = 2;</code>
     * @return string
     */
    public function getSimulationMetadata()
    {
        return $this->simulation_metadata;
    }

    /**
     * Generated from protobuf field <code>string simulation_metadata = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSimulationMetadata($var)
    {
        GPBUtil::checkString($var, True);
        $this->simulation_metadata = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string data = 3;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>string data = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, True);
        $this->data = $var;

        return $this;
    }

}

