# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gis/gis.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgis/gis.proto\x12\x03gis\"M\n\x12\x43reateNetworkInput\x12\x10\n\x08platform\x18\x01 \x01(\t\x12\x11\n\tcf_module\x18\x02 \x01(\t\x12\x12\n\nteo_module\x18\x03 \x01(\t\"T\n\x13\x43reateNetworkOutput\x12\x0f\n\x07road_nw\x18\x01 \x01(\t\x12\x15\n\rn_demand_dict\x18\x02 \x01(\t\x12\x15\n\rn_supply_dict\x18\x03 \x01(\t\"c\n\x14OptimizeNetworkInput\x12\x10\n\x08platform\x18\x01 \x01(\t\x12\x11\n\tcf_module\x18\x02 \x01(\t\x12\x12\n\nteo_module\x18\x03 \x01(\t\x12\x12\n\ngis_module\x18\x04 \x01(\t\"\xe3\x01\n\x15OptimizeNetworkOutput\x12\x19\n\x11res_sources_sinks\x18\x01 \x01(\t\x12\x0c\n\x04sums\x18\x02 \x01(\t\x12\x16\n\x0elosses_cost_kw\x18\x03 \x01(\t\x12\x1e\n\x16network_solution_nodes\x18\x04 \x01(\t\x12\x1e\n\x16network_solution_edges\x18\x05 \x01(\t\x12\x17\n\x0fpotential_edges\x18\x06 \x01(\t\x12\x17\n\x0fpotential_nodes\x18\x07 \x01(\t\x12\x17\n\x0fselected_agents\x18\x08 \x01(\t2\x9b\x01\n\tGISModule\x12\x43\n\x0e\x63reate_network\x12\x17.gis.CreateNetworkInput\x1a\x18.gis.CreateNetworkOutput\x12I\n\x10optimize_network\x12\x19.gis.OptimizeNetworkInput\x1a\x1a.gis.OptimizeNetworkOutputb\x06proto3')



_CREATENETWORKINPUT = DESCRIPTOR.message_types_by_name['CreateNetworkInput']
_CREATENETWORKOUTPUT = DESCRIPTOR.message_types_by_name['CreateNetworkOutput']
_OPTIMIZENETWORKINPUT = DESCRIPTOR.message_types_by_name['OptimizeNetworkInput']
_OPTIMIZENETWORKOUTPUT = DESCRIPTOR.message_types_by_name['OptimizeNetworkOutput']
CreateNetworkInput = _reflection.GeneratedProtocolMessageType('CreateNetworkInput', (_message.Message,), {
  'DESCRIPTOR' : _CREATENETWORKINPUT,
  '__module__' : 'gis.gis_pb2'
  # @@protoc_insertion_point(class_scope:gis.CreateNetworkInput)
  })
_sym_db.RegisterMessage(CreateNetworkInput)

CreateNetworkOutput = _reflection.GeneratedProtocolMessageType('CreateNetworkOutput', (_message.Message,), {
  'DESCRIPTOR' : _CREATENETWORKOUTPUT,
  '__module__' : 'gis.gis_pb2'
  # @@protoc_insertion_point(class_scope:gis.CreateNetworkOutput)
  })
_sym_db.RegisterMessage(CreateNetworkOutput)

OptimizeNetworkInput = _reflection.GeneratedProtocolMessageType('OptimizeNetworkInput', (_message.Message,), {
  'DESCRIPTOR' : _OPTIMIZENETWORKINPUT,
  '__module__' : 'gis.gis_pb2'
  # @@protoc_insertion_point(class_scope:gis.OptimizeNetworkInput)
  })
_sym_db.RegisterMessage(OptimizeNetworkInput)

OptimizeNetworkOutput = _reflection.GeneratedProtocolMessageType('OptimizeNetworkOutput', (_message.Message,), {
  'DESCRIPTOR' : _OPTIMIZENETWORKOUTPUT,
  '__module__' : 'gis.gis_pb2'
  # @@protoc_insertion_point(class_scope:gis.OptimizeNetworkOutput)
  })
_sym_db.RegisterMessage(OptimizeNetworkOutput)

_GISMODULE = DESCRIPTOR.services_by_name['GISModule']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATENETWORKINPUT._serialized_start=22
  _CREATENETWORKINPUT._serialized_end=99
  _CREATENETWORKOUTPUT._serialized_start=101
  _CREATENETWORKOUTPUT._serialized_end=185
  _OPTIMIZENETWORKINPUT._serialized_start=187
  _OPTIMIZENETWORKINPUT._serialized_end=286
  _OPTIMIZENETWORKOUTPUT._serialized_start=289
  _OPTIMIZENETWORKOUTPUT._serialized_end=516
  _GISMODULE._serialized_start=519
  _GISMODULE._serialized_end=674
# @@protoc_insertion_point(module_scope)
