# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from gis import gis_pb2 as gis_dot_gis__pb2


class GISModuleStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create_network = channel.unary_unary(
                '/gis.GISModule/create_network',
                request_serializer=gis_dot_gis__pb2.CreateNetworkInput.SerializeToString,
                response_deserializer=gis_dot_gis__pb2.CreateNetworkOutput.FromString,
                )
        self.optimize_network = channel.unary_unary(
                '/gis.GISModule/optimize_network',
                request_serializer=gis_dot_gis__pb2.OptimizeNetworkInput.SerializeToString,
                response_deserializer=gis_dot_gis__pb2.OptimizeNetworkOutput.FromString,
                )


class GISModuleServicer(object):
    """Missing associated documentation comment in .proto file."""

    def create_network(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def optimize_network(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GISModuleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create_network': grpc.unary_unary_rpc_method_handler(
                    servicer.create_network,
                    request_deserializer=gis_dot_gis__pb2.CreateNetworkInput.FromString,
                    response_serializer=gis_dot_gis__pb2.CreateNetworkOutput.SerializeToString,
            ),
            'optimize_network': grpc.unary_unary_rpc_method_handler(
                    servicer.optimize_network,
                    request_deserializer=gis_dot_gis__pb2.OptimizeNetworkInput.FromString,
                    response_serializer=gis_dot_gis__pb2.OptimizeNetworkOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gis.GISModule', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GISModule(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create_network(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gis.GISModule/create_network',
            gis_dot_gis__pb2.CreateNetworkInput.SerializeToString,
            gis_dot_gis__pb2.CreateNetworkOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def optimize_network(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gis.GISModule/optimize_network',
            gis_dot_gis__pb2.OptimizeNetworkInput.SerializeToString,
            gis_dot_gis__pb2.OptimizeNetworkOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
