# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: teo/teo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rteo/teo.proto\x12\x03teo\"J\n\x0f\x42uildModelInput\x12\x10\n\x08platform\x18\x01 \x01(\t\x12\x11\n\tcf_module\x18\x02 \x01(\t\x12\x12\n\ngis_module\x18\x03 \x01(\t\"\"\n\x10\x42uildModelOutput\x12\x0e\n\x06output\x18\x01 \x01(\t2F\n\tTEOModule\x12\x39\n\nbuildmodel\x12\x14.teo.BuildModelInput\x1a\x15.teo.BuildModelOutputb\x06proto3')



_BUILDMODELINPUT = DESCRIPTOR.message_types_by_name['BuildModelInput']
_BUILDMODELOUTPUT = DESCRIPTOR.message_types_by_name['BuildModelOutput']
BuildModelInput = _reflection.GeneratedProtocolMessageType('BuildModelInput', (_message.Message,), {
  'DESCRIPTOR' : _BUILDMODELINPUT,
  '__module__' : 'teo.teo_pb2'
  # @@protoc_insertion_point(class_scope:teo.BuildModelInput)
  })
_sym_db.RegisterMessage(BuildModelInput)

BuildModelOutput = _reflection.GeneratedProtocolMessageType('BuildModelOutput', (_message.Message,), {
  'DESCRIPTOR' : _BUILDMODELOUTPUT,
  '__module__' : 'teo.teo_pb2'
  # @@protoc_insertion_point(class_scope:teo.BuildModelOutput)
  })
_sym_db.RegisterMessage(BuildModelOutput)

_TEOMODULE = DESCRIPTOR.services_by_name['TEOModule']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BUILDMODELINPUT._serialized_start=22
  _BUILDMODELINPUT._serialized_end=96
  _BUILDMODELOUTPUT._serialized_start=98
  _BUILDMODELOUTPUT._serialized_end=132
  _TEOMODULE._serialized_start=134
  _TEOMODULE._serialized_end=204
# @@protoc_insertion_point(module_scope)
