<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market/market.proto

namespace GPBMetadata\Market;

class Market
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
˙
market/market.protomarket"
MarketInput
input (	"a
MarketInputRequest

gis_module (	
	cf_module (	

teo_module (	
platform (	"Í
ShortTermMarketResponse

Gn (	

Ln (	

Pn (	
QoE (	
optimal (	
plot_market_clearing (	

settlement (	
social_welfare_h (	
shadow_price	 (	
Tnm
 (	
agent_operational_cost (	"ç
LongTermMarketResponse

Gn (	

Ln (	

Pn (	
QoE (	
optimal (	

settlement (	
social_welfare_h (	
SPM (	
ADG	 (	
expensive_prod
 (	
shadow_price (	
Tnm (	
agent_operational_cost (	
report (	2‘
MarketModuleQ
RunShortTermMarket.market.MarketInputRequest.market.ShortTermMarketResponseP
RunShortTermMarketDirect.market.MarketInput.market.ShortTermMarketResponseO
RunLongTermMarket.market.MarketInputRequest.market.LongTermMarketResponseN
RunLongTermMarketDirect.market.MarketInput.market.LongTermMarketResponsebproto3'
        , true);

        static::$is_initialized = true;
    }
}

